version: "3.2"
services:
  app-dev:
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - app-deps:/usr/src/app/node_modules
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
      - mongo-config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
volumes:
  mongodata:
  mongo-config:
  app-deps:
