FROM node:14.16.0-alpine3.10 as builder

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python make musl-dev

COPY package.json yarn.lock ./

RUN yarn install

FROM node:14.16.0-alpine3.10

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY . .
CMD ["yarn", "start:dev"]
