FROM node:10-alpine as builder

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

FROM node:10-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY . .
CMD ["yarn", "start:dev"]
