FROM node:14.16.0-alpine3.10 as builder

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python make musl-dev

COPY package.json yarn.lock ./

RUN yarn install --prod

COPY . .

RUN yarn build

FROM node:14.16.0-alpine3.10

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/build ./build
COPY migrations ./migrations
COPY migrate-mongo-config.js migrate-mongo-setup.sh ./
COPY --from=builder /usr/src/app/node_modules ./node_modules

CMD ["node", "build/index.js"]
