# connection settings

# connect to MongoDB using the following URL
mongo-url = "mongodb://mongodb:27017/retrospect"
# connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://elastic-search:9200"]

namespace-exclude-regex = '^retrospect\.users'

direct-read-namespaces = [
  "retrospect.persons",
  "retrospect.location_instances",
  "retrospect.locations",
  "retrospect.locationtypes",
  "retrospect.relations",
  "retrospect.relationtypes",
]
