name: Jest tests

on:
  - push

jobs:
  build:
    name: Run Jest tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
